const IPCEvents = {
    COMPILE_SCSS: "HOLYMOD_COMPILE_SCSS",
    COMPILE_TYPESCRIPT: "HOLYMOD_COMPILE_TYPESCRIPT",
    COMPILE_JAVASCRIPT: "HOLYMOD_COMPILE_JAVASCRIPT",
    COMPILE_COFFEESCRIPT: "HOLYMOD_COMPILE_COFFEESCRIPT",
    GET_APP_PATH: "HOLYMOD_GET_APP_PATH",
    TOGGLE_DEV_TOOLS: "HOLYMOD_TOGGLE_DEV_TOOLS"
};

export default IPCEvents;